Project/Project/Models/Reservations.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project.Models
{
    public class Reservations
    {
        public int Id { get; set; }
        public int accID { get; set; }
        public int bbID { get; set; }
        public int Qty { get; set; }
        public DateTime ReserveDate { get; set; }
        public string BorrowersName { get; set; }
        public string BookTitle { get; set; }
    }
}

Project/Project/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Entity;
using Project.Models;
using System.Net;
using Project.Utils;

namespace Project.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index(string search = "", string id = "")
        {

            if (search != "")
            {
                return View(AccountsUtils.GetAccounts(0).Where(a => a.Name == search || a.Username ==search));
            }

            return View(AccountsUtils.GetAccounts(0));
        }

        public ActionResult Home()
        {
            return View();
        }

        public ActionResult Add(Accounts acc)
        {

            if (acc.Name != null)
            {
                AccountsUtils.Save(acc);
                return RedirectToAction("Index");
            }
            return View();
        }  

        public ActionResult Delete(int id)
        {
            AccountsUtils.DeleteConfirm(id);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Accounts acc)
        {
            return View(AccountsUtils.GetAccounts(acc.Id).FirstOrDefault());
        }

    }
}

Project/Project/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Entity;
using Project.Models;
using Project.Utils;

namespace Project.Controllers
{
    public class ReservationController : Controller
    {
        //
        // GET: /Reservation/

        public ActionResult Index(string search = "", string id = "")
        {

            if (search != "")
            {
                return View(ReservationUtils.GetReservations(0).Where(a => a.BorrowersName == search || a.BookTitle == search));
            }

            return View(ReservationUtils.GetReservations(0));
        }

        public ActionResult UserIndex(Accounts acc)
        {
            int Id = Convert.ToInt32(Session["LogedAccountId"]);
            Information info = new Information();
            using (var db = new DatabaseEntities1())
            {
                var allAccount = db.Accounts.FirstOrDefault(a => a.AccountId == Id);
                var allBook = db.Books.ToList();
                var allResrv = db.Reservations.Where(br => br.AccountId == Id).ToList();
                info.Account.Add(allAccount);
                info.Book.AddRange(allBook);

                info.BookReservation.AddRange(allResrv.Select(b =>
                    new Reservation
                    {
                        ReservationId = b.ReservationId,
                        AccountId = b.AccountId,
                        BookTitle = allBook.FirstOrDefault(book => book.BookId == b.BookId).Title,
                        BorrowersName = db.Accounts.FirstOrDefault(account => account.AccountId == b.AccountId).Name,
                        Quantity = (int)b.Quantity
                    }));
            }
            return View(info);
        }

        //public ActionResult User()
        //{
        //    return View();
        //}

        public ActionResult Reserve(int AccountId, int BookId, int Qty, DateTime date, string name, string title)
        {
            using (var db = new DatabaseEntities1())
            {
                var selected = db.Accounts.FirstOrDefault(x => x.AccountId == AccountId);
                db.Reservations.Add(new Reservation { AccountId = selected.AccountId, BookId = BookId, Quantity = Qty, ReservationDate = date, BorrowersName = name, BookTitle = title });
                db.SaveChanges();
            }
            return RedirectToAction("UserIndex", new { id = AccountId });
        }

        public ActionResult MyReservation()
        {
            string search=Session["LogedName"].ToString();
            if (search != "")
            {
                return View(ReservationUtils.GetReservations(0).Where(a => a.BorrowersName == search));
            }

            return View(ReservationUtils.GetReservations(0));
        }

        public ActionResult DeleteAll()
        {
            using (var db = new DatabaseEntities1())
            {

                foreach (var ent in db.Reservations)
                {
                    db.Reservations.Remove(ent);
                }

                db.SaveChanges();
            }

            return RedirectToAction("UserIndex");
        }

        public ActionResult Cancel(int id)
        {
            ReservationUtils.CancelConfirm(id);
            return RedirectToAction("UserIndex");
        }

        public ActionResult AdminDelete(int id)
        {
            ReservationUtils.CancelConfirm(id);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            ReservationUtils.CancelConfirm(id);
            return RedirectToAction("MyReservation");
        }
    }
}

Project/Project/Views/Reservation/Index.cshtml
@model IEnumerable<Project.Models.Reservations>

@{
    ViewBag.Title = "Index";
}
@Html.ActionLink("Home","Home","Admin")
@Html.ActionLink("Logout","Logout","Home")
<br /><br />
<h2>All Reservations</h2>
<br />
<form method="get" action="@Url.Action("Index", "Reservation")">
    <label>Search Book Title or Name </label>
    <input type="text" name="search" />
    <button type="submit">Search</button>
</form>
<br />
@Html.ActionLink("Delete All Reservation", "DeleteAll")
<br />
<table style="width:50%"> 
        <tr>
                <td><b>Res Id</td>
                <td><b>Name</td>
                <td><b>Book Title</td>
                <td><b>Quantity</td>
                <td><b>Reserve Date</td><td></td>
        </tr>
        @foreach (var x in Model)
        {
        <tr>
            <td>@Html.DisplayFor(item => x.Id)</td>
            <td>@Html.DisplayFor(item => x.BorrowersName)</td>
            <td>@Html.DisplayFor(item => x.BookTitle)</td>
            <td>@Html.DisplayFor(item => x.Qty)</td>
            <td>@Html.DisplayFor(item => x.ReserveDate)</td>

            <td>@Html.ActionLink("Delete", "AdminDelete", new { Id = x.Id })</td>
        </tr>
        }
    </table>

Project/Project/Views/Reservation/MyReservation.cshtml
@model IEnumerable<Project.Models.Reservations>
@{
    ViewBag.Title = "MyReservation";
}
@Html.ActionLink("Home","HomeIndex","Home")
@Html.ActionLink("Logout","Logout","Home")

<h2>My Book Reservations</h2>

<br />
<table style="width:40%">
    <tr>
        <td><b>Id</td>
        <td><b>Book Title</td>
        <td><b>Quantity</td>
        <td><b>Reservation Date</td>
        <td></td>
    </tr>
@foreach (var x in Model)
{
    <tr>
        <td>@Html.DisplayFor(item => x.Id)</td>
        <td>@Html.DisplayFor(item => x.BookTitle)</td>
        <td> @Html.DisplayFor(item => x.Qty)</td>
        <td>@Html.DisplayFor(item => x.ReserveDate)</td>
        <td>@Html.ActionLink("Delete", "Delete",  new { Id = x.Id })</td>
    </tr>
}
    </table>
<br />

Project/Project/Views/Reservation/UserIndex.cshtml
@model Project.Models.Information
@{
    ViewBag.Title = "View";
}
@Html.ActionLink("Home","HomeIndex","Home")
@Html.ActionLink("Logout","Logout","Home")
<br />
<br/>
<h2>
    @foreach (var x in Model.Account)
    {
        @Html.DisplayFor(item => x.Name)<text>, reserve a book now!</text>
        <br />
    }
</h2>
<br />
<br />
    <table>
        <tr>
            <td></td><td><b>Book Title</td><td><b>Quantity</td><td></td>
        </tr>
        @foreach (var x in Model.Book)
        {
            using (Html.BeginForm("Reserve", "Reservation", new
             {
                 AccountId = Model.Account.FirstOrDefault().AccountId,
                 BookId = x.BookId, name = Model.Account.FirstOrDefault().Name, title = x.Title, date = DateTime.Now
              }))
             {
                <tr>
                <td>@Html.DisplayFor(item => x.BookId)</td>
                <td>@Html.DisplayFor(item => x.Title)</td>
                <td>@Html.TextBox("Qty",null,new {style = "width:50px" })</td> 
                <td><input type='submit' value='Reserve' /></td>
                </tr>
               }
           }
    </table>
  
    <br />


<br />
<br />
<br />
<table style="width:40%">
    <tr>
        <td><b>Res Id</td>
        <td><b>Borrower</td>
        <td><b>Book Title</td>
        <td><b>Quantity</td>
        <td><b>Date</td>
        <td></td>
    </tr>
@foreach (var x in Model.BookReservation)
{
    <tr>
    <td>@Html.DisplayFor(item => x.ReservationId)</td>
    <td>@Html.DisplayFor(item => x.BorrowersName)</td>
    <td>@Html.DisplayFor(item => x.BookTitle)</td>
    <td>@Html.DisplayFor(item => x.Quantity)</td>
    <td>@Html.DisplayFor(item => x.ReservationDate)</td>
    <td>@Html.ActionLink("Cancel", "Cancel", new { Id = x.ReservationId })</td>
    </tr>
}
    </table>
<br />
<br />
<br />