Project/Project/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using Project.Entity;
using Project.Utils;

namespace Project.Controllers
{
    public class BookController : Controller
    {
        //
        // GET: /Book/

        public ActionResult Index(string search = "", string id = "")
        {
            if (search != "")
            {
                return View(BooksUtils.GetBooks(0).Where(x => x.BookTitle == search || x.BookAuthor == search));
            }
            return View(BooksUtils.GetBooks(0));
        }

        public ActionResult UserBookIndex(string search = "", string id = "")
        {
            if (search != "")
            {
                return View(BooksUtils.GetBooks(0).Where(x => x.BookTitle == search || x.BookAuthor == search));
            }
            return View(BooksUtils.GetBooks(0));
        }

        public ActionResult Add(Books book)
        {
            if (book.BookTitle != null)
            {
                BooksUtils.Save(book);
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(Books book)
        {
            return View(BooksUtils.GetBooks(book.Id).FirstOrDefault());
        }

        public ActionResult Delete(int id)
        {
            BooksUtils.DeleteConfirm(id);
            return RedirectToAction("Index");
        }
    }
}

Project/Project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Entity;
using Project.Models;
using Project.Utils;

namespace Project.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult HomeIndex()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Account acc)
        {
            if (ModelState.IsValid)
            {
                using (DatabaseEntities1 db = new DatabaseEntities1())
                {
                    var v = db.Accounts.Where(a => a.Username.Equals(acc.Username) && a.Password.Equals(acc.Password)).FirstOrDefault();
                    if (v != null)
                    {
                        Session["LogedAccountId"] = v.AccountId.ToString();
                        Session["LogedName"] = v.Name.ToString();
                        return RedirectToAction("AfterLogin");
                    }
                }
            }
            return View(acc);
        }

        public ActionResult AfterLogin(Account acc,string search)
        {
            using (var db = new DatabaseEntities1())
            {
                var current = db.Accounts.Where(a => a.AccountId.Equals(acc.AccountId)).FirstOrDefault();
                if (Session["LogedAccountId"] != null)
                {
                    if (Session["LogedName"].ToString() == "Admin")
                    {
                        return RedirectToAction("Home", "Admin");
                    }
                    else
                    {
                        return RedirectToAction("HomeIndex", "Home");
                    }
                }
                else
                {
                    return RedirectToAction("Login");
                }
            }
        }

        public ActionResult Logout()
        {
            return View("Login");
        }

        public ActionResult SignUp()
        {
            return View();
        }

        public ActionResult Add(Accounts acc)
        {

            if (acc.Name != null)
            {
                AccountsUtils.Save(acc);
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
    }
}

Project/Project/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Project.Entity;
using Project.Models;
using Project.Utils;

namespace Project.Controllers
{
    public class ReservationController : Controller
    {
        //
        // GET: /Reservation/

        public ActionResult Index(string search = "", string id = "")
        {

            if (search != "")
            {
                return View(ReservationUtils.GetReservations(0).Where(a => a.BorrowersName == search || a.BookTitle == search));
            }

            return View(ReservationUtils.GetReservations(0));
        }

        public ActionResult UserIndex(Accounts acc)
        {
            int Id = Convert.ToInt32(Session["LogedAccountId"]);
            Information info = new Information();
            using (var db = new DatabaseEntities1())
            {
                var allAccount = db.Accounts.FirstOrDefault(a => a.AccountId == Id);
                var allBook = db.Books.ToList();
                var allResrv = db.Reservations.Where(br => br.AccountId == Id).ToList();
                info.Account.Add(allAccount);
                info.Book.AddRange(allBook);

                info.BookReservation.AddRange(allResrv.Select(b =>
                    new Reservation
                    {
                        ReservationId = b.ReservationId,
                        AccountId = b.AccountId,
                        BookTitle = allBook.FirstOrDefault(book => book.BookId == b.BookId).Title,
                        BorrowersName = db.Accounts.FirstOrDefault(account => account.AccountId == b.AccountId).Name,
                        Quantity = (int)b.Quantity
                    }));
            }
            return View(info);
        }

        //public ActionResult User()
        //{
        //    return View();
        //}

        public ActionResult Reserve(int AccountId, int BookId, int Qty, DateTime date, string name, string title)
        {
            using (var db = new DatabaseEntities1())
            {
                var selected = db.Accounts.FirstOrDefault(x => x.AccountId == AccountId);
                db.Reservations.Add(new Reservation { AccountId = selected.AccountId, BookId = BookId, Quantity = Qty, ReservationDate = date, BorrowersName = name, BookTitle = title });
                db.SaveChanges();
            }
            return RedirectToAction("UserIndex", new { id = AccountId });
        }

        public ActionResult MyReservation()
        {
            string search=Session["LogedName"].ToString();
            if (search != "")
            {
                return View(ReservationUtils.GetReservations(0).Where(a => a.BorrowersName == search));
            }

            return View(ReservationUtils.GetReservations(0));
        }

        public ActionResult DeleteAll()
        {
            using (var db = new DatabaseEntities1())
            {

                foreach (var ent in db.Reservations)
                {
                    db.Reservations.Remove(ent);
                }

                db.SaveChanges();
            }

            return RedirectToAction("UserIndex");
        }

        public ActionResult Cancel(int id)
        {
            ReservationUtils.CancelConfirm(id);
            return RedirectToAction("UserIndex");
        }

        public ActionResult AdminDelete(int id)
        {
            ReservationUtils.CancelConfirm(id);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            ReservationUtils.CancelConfirm(id);
            return RedirectToAction("MyReservation");
        }
    }
}

Project/Project/Views/Home/HomeIndex.cshtml
@model Project.Models.Accounts

@Html.ActionLink("Logout","Logout","Home")

@if (Session["LogedName"] != null)
{ 
    <text>
        <h1>Welcome @Session["LogedName"].ToString()!</h1>
    </text>
    <text>
        <h2>View List of @Html.ActionLink("Books", "UserBookIndex", "Book")</h2>
    </text>
    <text>
        <h2>View @Html.ActionLink("My Reservation", "MyReservation", "Reservation")</h2>
    </text>
}

Project/Project/Views/Home/Login.cshtml
@model Project.Models.Accounts

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm("Login", "Home", FormMethod.Post))
{ 
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)

    if(@ViewBag.Message != null)
    {
        <div style="border:1px solid red">
            @ViewBag.Message
        </div>
    }
    <table>
        <tr>
            <td><label>Username: </label></td>
            <td colspan="2"><input type="text" name="username" /></td>
            <td>@Html.ValidationMessageFor(a=>a.Username)</td>
        </tr>
        <tr></tr>
        <tr>
            <td><label>Password: </label></td>
            <td colspan="2"><input type="password" name="password" /></td>
            <td>@Html.ValidationMessageFor(a=> a.Password)</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Login" /> 
            </td>
            <td><h3>@Html.ActionLink("Sign-up", "SignUp", "Home")</h3></td>
        </tr>
    </table>
}

Project/Project/Views/Home/SignUp.cshtml
@{
    ViewBag.Title = "SignUp";
}

<h2>Registration Page</h2>
@model Project.Models.Accounts

@using(Html.BeginForm("Add","Home"))
{
    <table>
        <tr>
            <td>@Html.LabelFor(asd => asd.Id)</td>
            <td>@Html.EditorFor(asd => asd.Id)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(asd=>asd.Username)</td>
            <td>@Html.EditorFor(asd=>asd.Username)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(asd => asd.Password)</td>
            <td>@Html.EditorFor(asd => asd.Password)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(asd => asd.Name)</td>
            <td>@Html.EditorFor(asd => asd.Name)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(asd => asd.Age)</td>
            <td>@Html.EditorFor(asd => asd.Age)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(asd => asd.Address)</td>
            <td>@Html.EditorFor(asd => asd.Address) </td>
        </tr>
    </table>
<button type="submit">Submit</button>
}